spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb?useUnicode=true&characterEncoding=UTF-8
    username: infojudicial
    password: nemoEncontrado$$1
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update